# Generated by Django 3.2.3 on 2021-08-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210826_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='completeby',
            field=models.DateField(),
        ),
    ]
