# Generated by Django 3.2.3 on 2021-08-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_completeby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completeby',
            new_name='bydate',
        ),
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
