# Generated by Django 3.2.3 on 2021-08-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210826_2318'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='bytime',
            field=models.TimeField(auto_now=True),
        ),
    ]
