# Generated by Django 3.2.3 on 2021-08-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_bytime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='bytime',
            field=models.TimeField(),
        ),
    ]
