# Generated by Django 3.2.3 on 2021-09-01 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
