# Generated by Django 3.2.3 on 2021-09-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='staff',
        ),
    ]
