# Generated by Django 3.2.3 on 2021-09-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_auto_20210903_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
